ソフトマックス関数 ①~③の数式に該当するソースコードを示し、一行づつ処理の説明をせよ。

In [1]:
# ①は関数宣言と同義
def softmax(x):
    if x.ndim == 2: # 変数xの次元数が2なら行列計算
        x = x.T # 転置、行でまとまっているデータを列方向へ変換し、一気に計算するため
        x = x - np.max(x, axis=0) # オーバーフロー対策で列方向の最大値を引く(元の行方向)
        y = np.exp(x) / np.sum(np.exp(x), axis=0) # ②/③
        return y.T # 転置を戻す
    x = x - np.max(x) # オーバーフロー対策
    return np.exp(x) / np.sum(np.exp(x)) # ②/③

In [2]:
import numpy as np

# 1次元
x = np.array([1, 1, 1])
y = softmax(x)
y

array([0.33333333, 0.33333333, 0.33333333])

In [3]:
# 2次元
x = np.array([[1, 1, 1], [1, 2, 3]])
y = softmax(x)
y

array([[0.33333333, 0.33333333, 0.33333333],
       [0.09003057, 0.24472847, 0.66524096]])

In [4]:
np.exp(x.T)

array([[ 2.71828183,  2.71828183],
       [ 2.71828183,  7.3890561 ],
       [ 2.71828183, 20.08553692]])

In [5]:
np.sum(np.exp(x.T), axis=0)

array([ 8.15484549, 30.19287485])

交差エントロピー ①~③の数式に該当するソースコードを示し、一行づつ処理の説明をせよ。

In [9]:
# 2つの分布が似ていると交差エントロピー誤差が小さくなる
def cross_entropy_error(d, y):
    if y.ndim == 1:
        print(d)
        d = d.reshape(1, d.size) # []で囲う
        print(d)
        y = y.reshape(1, y.size) # []で囲う
    if d.size == y.size:
        # 正解ラベルが1つとすると、計算するのは最大箇所の1つで良い
        # 配列で、一番大きい要素のインデックスを返す
        # 推定値が0.8でも関係なく、最大値なら1とみなす
        d = d.argmax(axis=1)
    batch_size = y.shape[0] # データ数(バッチサイズ)
    # 1e-7を足すことで、log計算が-∞にならないように
    return -np.sum(np.log(y[np.arange(batch_size), d] + 1e-7)) / batch_size

In [10]:

# 1次元
z = np.array([0.8, 0.1, 0.1]) #誤差算出用ダミー
y = np.array([1, 0, 0]) # 正解
e = cross_entropy_error(z, y)
e

[0.8 0.1 0.1]
[[0.8 0.1 0.1]]


-9.999999505838704e-08

In [11]:

# 2次元
z = np.array([[0.8, 0.1, 0.1], [0.7, 0.2, 0.1]]) #誤差算出用ダミー
y = np.array([[1, 0, 0], [1, 0, 0]]) # 正解
e = cross_entropy_error(z, y)
e

-9.999999505838704e-08