Section1：入力層～中間層

In [1]:
import numpy as np

# 入力層2つ、中間層1つで考える

x = np.array([4, 5])
W = np.array([[0.1], [0.2]])
b = 0.5

u = np.dot(x, W) + b
u

array([1.9])

In [2]:
(4 * 0.1 + 5 * 0.2) + 0.5

1.9

In [7]:

# 入力層2つ、中間層2つで考える

x = np.array([4, 5])
W = np.array([[0.1, 0.3], [0.2, 0.3]])
b = np.array([0.5, 0.4])

u = np.dot(x, W) + b
# 上の中間層への入力は最初と同じ1.9
u

array([1.9, 3.1])

In [8]:
# 1行目が、入力1を各中間層へ伝えるときの重み
print(W)

[[0.1 0.3]
 [0.2 0.3]]
